### PR TITLE
app.hooks global hooks

### LINKED ISSUE #119: service.hooks() did not run as expected
github feathers-hooks master was used

```javascript
const feathers = require('feathers');
const hooks = require('feathers-hooks');
const util = require('util');

const app = feathers()
  .configure(hooks())
  .configure(services);

const log = [];

// a random service is configured

function services () {
  this.use('/messages', {
    before: {
      all: (hook) => { log.push('service.before.all') },
      create: (hook) => { log.push('service.before.create'); }
    },
    after: {
      create: hook => { log.push('service.after.create'); }
    },
    create (data, params) {
      log.push('create method runs');
      return Promise.resolve();
    }
  });
}

// then the stats monitor hooks in

app.service('messages').hooks({
  before: {
    all: (hook) => { log.push('service.hooks.before.all'); }
  },
  after: {
    all: (hook) => { log.push('service.hooks.after.all'); }
  },
  error: {
    all: (hook) => { log.push('service.hooks.error.all'); }
  }
});

// a hook is added dynamically

app.service('messages').after({
  all (hook) { log.push('service.after.all'); }
});

// call a method

const service = app.service('messages');
service.create({ value: 1 }, { query: {} })
  .then(() => console.log(log));
```

gave

```text
[ 'service.before.all',
  'service.before.create',
  'service.hooks.before.all',
  'create method runs',
  'service.after.create',
  'service.hooks.after.all',
  'service.after.all' ]
```

expected was 

```text
[ 'service.hooks.before.all',
  'service.before.all',
  'service.before.create',
  'create method runs',
  'service.after.create',
  'service.after.all',
  'service.hooks.after.all' ]
```

I may be blind again.

### PR DESCRIPTION
**Pull request by daffl**
This pull request adds `app.hooks` which allows to register global `before`, `after` and `error` hooks that run for every service.

__Note:__ App `before` hooks will always run before all other service `before` hooks. App `after` and `error` hooks will run after all service specific `after` and `error` hooks.

For example logging the duration of every service method execution can be done like this:

```js
app.hooks({
  before(hook) {
    hook.start = new Date().getTime();
  },

  after(hook) {
    const duration = new Date().getTime() - hook.start;

    console.log(`${hook.method} execution took ${duration}ms`);
  }
});
```

A global service error handler that logs the error can look like this:

```js
app.hooks({
  error(hook) {
    console.error(`Error in ${hook.method}`, error);
  }
});
```

Also closes #119

### CODE REVIEW

**Comment by marshallswain** [comment]
LGTM

**Comment by ekryski** [comment]
:shipit:

**Comment by eddyystop** [comment]
I tried the feathers-hooks/app-hooks branch. I modified https://github.com/feathersjs/feathers-hooks/issues/119 as follows to match your post, but the hooks did not get called.

```javascript
app.hooks({
  before(hook) { log.push('app.hooks.before.all'); },
  after(hook) { log.push('app.hooks.after.all'); },
  error(hook) { log.push('app.hooks.error.all');  }
});
```

I also tried the syntax `before: (hook) => { log.push('app.hooks.before.all'); },` (duh) and ` before: { all: (hook) => { log.push('app.hooks.before.all'); } },`

I debugged a bunch. feathers-commons is used in `const hooks = utils.convertHookData(obj);` Do I need to use the latest from GitHub?

You're likely getting tired of my error-prone questions on this. I certainly am.

**Comment by daffl** [comment]
@eddyystop Not at all. And you were absolutely right, this didn't work at all. The tests didn't catch it because I only tested it with `get` which is a method on the `app` object. It didn't work for any other service method however. I pushed a fix and ran it with a test like this:

```js
const feathers = require('feathers');
const hooks = require('./lib/hooks');

const app = feathers()
  .configure(hooks())
  .use('/messages', {
    create (data, params) {
      log.push('create method runs');
      return Promise.resolve();
    }
  });

const log = [];

app.hooks({
  before (hook) { log.push('app.hooks.before.all'); },
  after (hook) { log.push('app.hooks.after.all'); },
  error (hook) { log.push('app.hooks.error.all'); }
});

app.service('messages').hooks({
  before: {
    all (hook) { log.push('service.hooks.before.all'); }
  },
  after: {
    all (hook) { log.push('service.hooks.after.all'); }
  },
  error: {
    all (hook) { log.push('service.hooks.error.all'); }
  }
});

// a hook is added dynamically
app.service('messages').after({
  all (hook) { log.push('service.after.all'); }
});

// call a method

const service = app.service('messages');
service.create({ value: 1 }, { query: {} })
  .then(() => console.log(log));
```

And it now prints the expected:

```
[ 'app.hooks.before.all',
  'service.hooks.before.all',
  'create method runs',
  'service.hooks.after.all',
  'service.after.all',
  'app.hooks.after.all' ]
```

**Comment by eddyystop** [comment]
My heart went pitter-patter when I saw those results. :)

**Comment by eddyystop** [comment]
`hook.app` does not exist when  an `app.hooks` hook is called. I need `hook.app.services` to determine the route of the service being called.

**Comment by daffl** [comment]
Are you sure? They are treated exactly the same and when I just tested it `hook.app` seemed to work fine everywhere. I used this example:

```js
const feathers = require('feathers');
const hooks = require('./lib/hooks');

const app = feathers()
  .configure(hooks())
  .use('/messages', {
    create (data, params) {
      log.push('create method runs');
      return Promise.resolve();
    }
  });

app.set('testvalue', 'testing');

const log = [];

app.hooks({
  before (hook) {
    log.push('app.hooks.before.all ' + hook.app.get('testvalue'));
  },
  after (hook) {
    log.push('app.hooks.after.all ' + hook.app.get('testvalue'));
  }
});

app.service('messages').hooks({
  before: {
    all (hook) {
      log.push('service.hooks.before.all ' + hook.app.get('testvalue'));
    }
  },
  after: {
    all (hook) {
      log.push('service.hooks.after.all ' + hook.app.get('testvalue'));
    }
  }
});

// a hook is added dynamically
app.service('messages').after({
  all (hook) { log.push('service.after.all ' + hook.app.get('testvalue')); }
});

// call a method

const service = app.service('messages');
service.create({ value: 1 }, { query: {} })
  .then(() => console.log(log));
```

Which prints

```js
[ 'app.hooks.before.all testing',
  'service.hooks.before.all testing',
  'create method runs',
  'service.hooks.after.all testing',
  'service.after.all testing',
  'app.hooks.after.all testing' ]
```

**Comment by daffl** [comment]
You might have to reinstall your node modules actually to get the latest version of feathers-commons (>= `0.7.7`) which is used here to set the app. `rm -rf node_modules && npm install` should do it.

**Comment by ekryski** [comment]
Good catch @eddyystop. My bad on the premature :shipit:. For bigger changes it's probably better if the reviewer actually pulls down and tries it out I guess.

**Pull request merged**
