### PR TITLE
making after hooks work even if the params argument was missing

### LINKED ISSUE #19: After hooks fail if params was missing on the original service method

### PR DESCRIPTION
**Pull request by ekryski**
This fixes #19. Still need to add a test for this

### CODE REVIEW

**Comment by daffl** [comment]
This is a good fix (with tests added) although having the parameters optional is turning out to be a big hassle . So many extra cases and bugs just so you don't have to type `{}, `.

**Comment by ekryski** [comment]
I know... :-(. I'm 50/50 on it right now. I'll have tests for this shortly. I actually need this fix asap.

**Comment by daffl** [comment]
If you're really that much against typing `{}, ` :wink:
Tests should be pretty easy once those are in I'll push a new release.

**Comment by daffl** [comment]
This is probably related to https://github.com/feathersjs/feathers/issues/113. I think that if we always normalize and validate method parameters beforehand all hooks should work.

**Comment by ekryski** [comment]
@daffl yes it seems to be causing a lot work arounds the fact that params can be optional. We should make it required that you pass at least `{}`.

**Comment by daffl** [comment]
I agree. As @marshallswain pointed out though, it is still easy to break the server by sending the wrong arguments through the socket.

**Comment by ekryski** [comment]
Ya I saw that :cry:. Let's make it required and then we can emit nice errors telling people that they need to at least pass `{}`. I'm now caught up on sleep and looking to do some coding this afternoon/evening.

**Comment by ekryski** [comment]
We should actually use the argument normalization from [feathers-commons](https://github.com/feathersjs/feathers-commons) and perform argument normalization on [this line](https://github.com/feathersjs/feathers-hooks/blob/master/lib/utils.js#L43)

**Comment by daffl** [comment]
This has been done and is released in version 1.1.0.

**Pull request closed without merging**
