### PR TITLE
adding ability to remove from result.data object

### PR DESCRIPTION
**Pull request by ekryski**
This is a workaround for #63 for auth. Adding a scope option would require more work.

### CODE REVIEW

**Comment by marshallswain** [comment]
:+1: :shipit:

**Comment by daffl** [comment]
Wy not just allow nested paths like `.after({ get: remove('user.password') })`?

**Comment by marshallswain** [comment]
That's what I was thinking.

**Comment by ekryski** [comment]
Ya I think that is the best solution. Do you guys have an idea on how best to implement it? I'd like to ship this as is and come back to it in #63. This is holding up auth 0.7, which is holding up the docs and generator updates.

**Pull request merged**
