### PR TITLE
Do not throw an error when a field that is supposed to be lowercased is undefined

### PR DESCRIPTION
**Pull request by gurisko**
This solves an issue when you have a hook:
```javascript
all: [
  hooks.lowerCase('email', 'username')
]
```
and you do not receive data that are supposed to be lowercased. Currently it throws `TypeError: Cannot call method 'toLowerCase' of undefined`.

### CODE REVIEW

**Comment by ekryski** [comment]
That's not ideal. @gurisko thanks for the fix. I'm not sure if we should ignore the field if it's not a string or throw an error. I think the former (your fix) is probably better.

Would be sweet if you can add a test for this case :grin:

**Comment by gurisko** [comment]
@ekryski Yes, let me add a test later today.

**Comment by gurisko** [comment]
@ekryski I guess you are right about ignoring the field if it's not a string. How about we go with something like:
* Ignore the field when it is `undefined`
* Throw an error when it is not a string
* Execute `lowerCase()` when it is a string

**Comment by ekryski** [comment]
@gurisko perfect!

**Comment by gurisko** [comment]
@ekryski Could you please review whether is better this time or not? Thanks!

**Comment by ekryski** [comment]
Awesome!! Thanks @gurisko! 😄

**Comment by ekryski** [comment]
v1.5.2 released with this fix. Thanks again ❤️

**Pull request merged**
