### PR TITLE
Should remove hook.params.provider to act as an internal call (#76)

### LINKED ISSUE #76: Should remove hook.params.provider to act as an internal call
Because we are calling `get` internally, we should remove `hook.params.provider`.
[..../v1.5.3/src/bundled.js#L235](https://github.com/feathersjs/feathers-hooks/blob/v1.5.3/src/bundled.js#L235)

### PR DESCRIPTION
**Pull request by JmeHsieh**
Fix #76

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the PR! It makes sense but I'm wondering if removing the provider would have unintended side effects. For example, `remove` hooks (e.g. to remove hashed passwords) also won't run if the provider isn't set. Maybe we could add a property in `params` (`params.disable = false;`) that alternatively to the provider indicates to skip the `disable` hook.

**Comment by JmeHsieh** [comment]
Thanks for pointing that out!

As I understood, Feathers checks the existence of `provider` to determine whether it is an internal or external call, right? (Like [here1](https://github.com/feathersjs/feathers-authentication/blob/d4f341d81f094336a8bf8eec524f1305195844ee/src/services/token/index.js#L30)  and [here2](https://github.com/feathersjs/feathers-authentication/blob/5cd6f04cd3db4c4149dafdc3039d5f2bfdf574e6/src/hooks/restrict-to-owner.js#L20).) 
Also, [here3](https://github.com/feathersjs/feathers-authentication/blob/5cd6f04cd3db4c4149dafdc3039d5f2bfdf574e6/src/hooks/restrict-to-roles.js#L69) manually set provider to undefined to act as an internal call.

Could you elaborate for me why the `remove` hooks run only if provider is set? 
(or maybe I should ask @ekryski ?)

Thanks!

**Comment by daffl** [comment]
For the `remove` hook the reason is pretty simple. You need to be able to retrieve the data without removed fields to e.g. compare passwords but you don't want to send the password on external calls. In the `restrictToRoles` hook the provider has to be set to `undefined` to avoid infinite loops because it will just try to continue to check the roles forever. I think the specific combination of `disable` + `populate` could be handled with the flag I suggested though.

**Comment by daffl** [comment]
Thank you again for the PR but I am going to close it. We will implement the `disable` functionality I mentioned instead in the new [feathers-hooks-common](https://github.com/feathersjs/feathers-hooks-common/)

**Pull request closed without merging**
